on:
  push:
    branches:
      - main

jobs:
  perform-auth-export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # - uses: "google-github-actions/auth@v2"
      #   with:
      #     credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - name: Install dependencies
        run: |
          npm i
      - name: Modify export to sleep for 5 minutes in between batches
        run: |
          sed -i 's/const userList = ret.body.users;/const userList = ret.body.users; await new Promise((res, _) => setTimeout(res, 300_000))/g' node_modules/firebase-tools/lib/accountExporter.js
        shell: bash
      - name: Run auth:export
        run: |
          node --version
          npm run firebase:version
          npm run auth:export -- --project ${{ secrets.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
